### ISSUE TITLE
[jobs_notify] Again raspi chromedriver connection timesout

### ISSUE THREAD

**Issue by rockycookie** [lukeZhangMengxi/raspi_scripts#6]
```
2020-07-14 19:31:52,411 - Job notifier exited unexpectedly
Traceback (most recent call last):
  File "/home/pi/workspace/raspi_scripts/jobs_notify/posters/amz.py", line 18, in search_amz_newgrad_recent_10
    driver.get(url)
  File "/home/pi/workspace/raspi_scripts/jobs_notify/env/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/pi/workspace/raspi_scripts/jobs_notify/env/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/pi/workspace/raspi_scripts/jobs_notify/env/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: cannot determine loading status
from timeout: Timed out receiving message from renderer: -1344.754
  (Session info: chrome=78.0.3904.108)
  (Driver info: chromedriver=2.25 (e0da1e9caa7c8f3da3519963a9ea32abba43c7c8),platform=Linux 4.19.97-v7+ armv7l)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "jobs_notify.py", line 72, in <module>
    if search_funcs[poster](args['url'], args['key_words']):
  File "/home/pi/workspace/raspi_scripts/jobs_notify/posters/amz.py", line 22, in search_amz_newgrad_recent_10
    driver.close()
  File "/home/pi/workspace/raspi_scripts/jobs_notify/env/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 688, in close
    self.execute(Command.CLOSE)
  File "/home/pi/workspace/raspi_scripts/jobs_notify/env/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/pi/workspace/raspi_scripts/jobs_notify/env/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: failed to close window in 20 seconds
  (Session info: chrome=78.0.3904.108)
  (Driver info: chromedriver=2.25 (e0da1e9caa7c8f3da3519963a9ea32abba43c7c8),platform=Linux 4.19.97-v7+ armv7l)
```

**Comment by rockycookie** [comment]
It turns out the error was caused simply by the overheating RaspberryPi board. It might be a little bit overloaded for my old Pi. But a simply reboot get everything working on my side.

While, we get another problem 
```
smtplib.SMTPDataError: (421, b'4.3.0 Temporary System Problem.  Try again later (10). j5sm2981239pfa.5 - gsmtp')
```
which caused the notifier exited again~

**Comment by rockycookie** [comment]
Again, this issue is fixed by shutdown my Pi and restart after cool down.

The Gmail SMTP server error is recorded on #7
